### ISSUE TITLE
MRAA DI9 nicht lesbar

### ISSUE THREAD

**Issue by thysce** [mirkowi/TERANiS-PLC#2]
Beim lesen von IX(1,1) erhält man immer den Wert der USED_LED statt des Eingangswertes des Eingabemoduls des IOT-Gateways

**Comment by mirkowi** [comment]
Das ist richtig so, da die USER_LED und der Eingang auf dem selben GPIO-Port liegen.
Wenn man den Eingang nutzen möchte, darf man den Port nicht als Ausgang konfigurieren.

**Comment by thysce** [comment]
Ich möchte diesen Eingang nun aber in einem Projekt nutzen. Daher möchte ich den Code derart ändern, dass standardmäßig Pin13=DI9 statt Pin13=LED.

**Comment by mirkowi** [comment]
Die I/O Konfiguration muss sowieso meist projektspezifisch angepasst werden, also kein Problem.
Das im Standard ist nur ein Beispiel.

**Comment by thysce** [comment]
Okay, das bedeutet folglich, dass die Programmierung für jeden Anwendungsfall neu überprüft werden muss.
